server:
  port: 8090
  servlet:
    context-path: /crm

spring:
  application:
    name: crm application
    version: 1.0

security:
  oauth2:
    client:
      client-id: crm
      client-secret: crm_secret
      access-token-uri: http://localhost:8888/oauth/token
      user-authorization-uri: http://localhost:8888/oauth/authorize
    resource:
      jwt:
        key-uri: http://localhost:8888/oauth/token_key

oa:
  profile-uri: http://localhost:8080/oa/system/profile