server:
  port: 8086
  servlet:
    context-path: /oa

spring:
  application:
    name: oa application
    version: 1.0

security:
  oauth2:
    client:
      client-id: clientapp
      client-secret: 12345678
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      jwt:
        key-uri: http://localhost:8080/oauth/token_key
        key-value: eforce-secret

crm:
  profile-uri: http://localhost:8090/crm/system/profile